/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_LINUX_USER_GENERATED_TRACERS_H
#define TRACE_LINUX_USER_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_SIGNAL_TABLE_INIT_EVENT;
extern TraceEvent _TRACE_SIGNAL_DO_SIGACTION_GUEST_EVENT;
extern TraceEvent _TRACE_SIGNAL_DO_SIGACTION_HOST_EVENT;
extern TraceEvent _TRACE_USER_SETUP_FRAME_EVENT;
extern TraceEvent _TRACE_USER_SETUP_RT_FRAME_EVENT;
extern TraceEvent _TRACE_USER_DO_RT_SIGRETURN_EVENT;
extern TraceEvent _TRACE_USER_DO_SIGRETURN_EVENT;
extern TraceEvent _TRACE_USER_FORCE_SIG_EVENT;
extern TraceEvent _TRACE_USER_HANDLE_SIGNAL_EVENT;
extern TraceEvent _TRACE_USER_HOST_SIGNAL_EVENT;
extern TraceEvent _TRACE_USER_QUEUE_SIGNAL_EVENT;
extern TraceEvent _TRACE_USER_S390X_RESTORE_SIGREGS_EVENT;
extern TraceEvent _TRACE_TARGET_MPROTECT_EVENT;
extern TraceEvent _TRACE_TARGET_MMAP_EVENT;
extern TraceEvent _TRACE_TARGET_MMAP_COMPLETE_EVENT;
extern TraceEvent _TRACE_TARGET_MUNMAP_EVENT;
extern uint16_t _TRACE_SIGNAL_TABLE_INIT_DSTATE;
extern uint16_t _TRACE_SIGNAL_DO_SIGACTION_GUEST_DSTATE;
extern uint16_t _TRACE_SIGNAL_DO_SIGACTION_HOST_DSTATE;
extern uint16_t _TRACE_USER_SETUP_FRAME_DSTATE;
extern uint16_t _TRACE_USER_SETUP_RT_FRAME_DSTATE;
extern uint16_t _TRACE_USER_DO_RT_SIGRETURN_DSTATE;
extern uint16_t _TRACE_USER_DO_SIGRETURN_DSTATE;
extern uint16_t _TRACE_USER_FORCE_SIG_DSTATE;
extern uint16_t _TRACE_USER_HANDLE_SIGNAL_DSTATE;
extern uint16_t _TRACE_USER_HOST_SIGNAL_DSTATE;
extern uint16_t _TRACE_USER_QUEUE_SIGNAL_DSTATE;
extern uint16_t _TRACE_USER_S390X_RESTORE_SIGREGS_DSTATE;
extern uint16_t _TRACE_TARGET_MPROTECT_DSTATE;
extern uint16_t _TRACE_TARGET_MMAP_DSTATE;
extern uint16_t _TRACE_TARGET_MMAP_COMPLETE_DSTATE;
extern uint16_t _TRACE_TARGET_MUNMAP_DSTATE;
#define TRACE_SIGNAL_TABLE_INIT_ENABLED 1
#define TRACE_SIGNAL_DO_SIGACTION_GUEST_ENABLED 1
#define TRACE_SIGNAL_DO_SIGACTION_HOST_ENABLED 1
#define TRACE_USER_SETUP_FRAME_ENABLED 1
#define TRACE_USER_SETUP_RT_FRAME_ENABLED 1
#define TRACE_USER_DO_RT_SIGRETURN_ENABLED 1
#define TRACE_USER_DO_SIGRETURN_ENABLED 1
#define TRACE_USER_FORCE_SIG_ENABLED 1
#define TRACE_USER_HANDLE_SIGNAL_ENABLED 1
#define TRACE_USER_HOST_SIGNAL_ENABLED 1
#define TRACE_USER_QUEUE_SIGNAL_ENABLED 1
#define TRACE_USER_S390X_RESTORE_SIGREGS_ENABLED 1
#define TRACE_TARGET_MPROTECT_ENABLED 1
#define TRACE_TARGET_MMAP_ENABLED 1
#define TRACE_TARGET_MMAP_COMPLETE_ENABLED 1
#define TRACE_TARGET_MUNMAP_ENABLED 1

#define TRACE_SIGNAL_TABLE_INIT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_signal_table_init(int i)
{
}

static inline void trace_signal_table_init(int i)
{
    if (true) {
        _nocheck__trace_signal_table_init(i);
    }
}

#define TRACE_SIGNAL_DO_SIGACTION_GUEST_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_signal_do_sigaction_guest(int sig, int max)
{
}

static inline void trace_signal_do_sigaction_guest(int sig, int max)
{
    if (true) {
        _nocheck__trace_signal_do_sigaction_guest(sig, max);
    }
}

#define TRACE_SIGNAL_DO_SIGACTION_HOST_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_signal_do_sigaction_host(int sig, int max)
{
}

static inline void trace_signal_do_sigaction_host(int sig, int max)
{
    if (true) {
        _nocheck__trace_signal_do_sigaction_host(sig, max);
    }
}

#define TRACE_USER_SETUP_FRAME_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_setup_frame(void * env, uint64_t frame_addr)
{
}

static inline void trace_user_setup_frame(void * env, uint64_t frame_addr)
{
    if (true) {
        _nocheck__trace_user_setup_frame(env, frame_addr);
    }
}

#define TRACE_USER_SETUP_RT_FRAME_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_setup_rt_frame(void * env, uint64_t frame_addr)
{
}

static inline void trace_user_setup_rt_frame(void * env, uint64_t frame_addr)
{
    if (true) {
        _nocheck__trace_user_setup_rt_frame(env, frame_addr);
    }
}

#define TRACE_USER_DO_RT_SIGRETURN_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_do_rt_sigreturn(void * env, uint64_t frame_addr)
{
}

static inline void trace_user_do_rt_sigreturn(void * env, uint64_t frame_addr)
{
    if (true) {
        _nocheck__trace_user_do_rt_sigreturn(env, frame_addr);
    }
}

#define TRACE_USER_DO_SIGRETURN_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_do_sigreturn(void * env, uint64_t frame_addr)
{
}

static inline void trace_user_do_sigreturn(void * env, uint64_t frame_addr)
{
    if (true) {
        _nocheck__trace_user_do_sigreturn(env, frame_addr);
    }
}

#define TRACE_USER_FORCE_SIG_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_force_sig(void * env, int target_sig, int host_sig)
{
}

static inline void trace_user_force_sig(void * env, int target_sig, int host_sig)
{
    if (true) {
        _nocheck__trace_user_force_sig(env, target_sig, host_sig);
    }
}

#define TRACE_USER_HANDLE_SIGNAL_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_handle_signal(void * env, int target_sig)
{
}

static inline void trace_user_handle_signal(void * env, int target_sig)
{
    if (true) {
        _nocheck__trace_user_handle_signal(env, target_sig);
    }
}

#define TRACE_USER_HOST_SIGNAL_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_host_signal(void * env, int host_sig, int target_sig)
{
}

static inline void trace_user_host_signal(void * env, int host_sig, int target_sig)
{
    if (true) {
        _nocheck__trace_user_host_signal(env, host_sig, target_sig);
    }
}

#define TRACE_USER_QUEUE_SIGNAL_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_queue_signal(void * env, int target_sig)
{
}

static inline void trace_user_queue_signal(void * env, int target_sig)
{
    if (true) {
        _nocheck__trace_user_queue_signal(env, target_sig);
    }
}

#define TRACE_USER_S390X_RESTORE_SIGREGS_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_user_s390x_restore_sigregs(void * env, uint64_t sc_psw_addr, uint64_t env_psw_addr)
{
}

static inline void trace_user_s390x_restore_sigregs(void * env, uint64_t sc_psw_addr, uint64_t env_psw_addr)
{
    if (true) {
        _nocheck__trace_user_s390x_restore_sigregs(env, sc_psw_addr, env_psw_addr);
    }
}

#define TRACE_TARGET_MPROTECT_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_target_mprotect(uint64_t start, uint64_t len, int flags)
{
}

static inline void trace_target_mprotect(uint64_t start, uint64_t len, int flags)
{
    if (true) {
        _nocheck__trace_target_mprotect(start, len, flags);
    }
}

#define TRACE_TARGET_MMAP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_target_mmap(uint64_t start, uint64_t len, int pflags, int mflags, int fd, uint64_t offset)
{
}

static inline void trace_target_mmap(uint64_t start, uint64_t len, int pflags, int mflags, int fd, uint64_t offset)
{
    if (true) {
        _nocheck__trace_target_mmap(start, len, pflags, mflags, fd, offset);
    }
}

#define TRACE_TARGET_MMAP_COMPLETE_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_target_mmap_complete(uint64_t retaddr)
{
}

static inline void trace_target_mmap_complete(uint64_t retaddr)
{
    if (true) {
        _nocheck__trace_target_mmap_complete(retaddr);
    }
}

#define TRACE_TARGET_MUNMAP_BACKEND_DSTATE() ( \
    false)

static inline void _nocheck__trace_target_munmap(uint64_t start, uint64_t len)
{
}

static inline void trace_target_munmap(uint64_t start, uint64_t len)
{
    if (true) {
        _nocheck__trace_target_munmap(start, len);
    }
}
#endif /* TRACE_LINUX_USER_GENERATED_TRACERS_H */
